/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited. It is normally generated by Next.js on
// first run; checked in so typecheck works before the first `next dev`.
